# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-ModBT
version:      0.018
version_from: lib/Apache2/ModBT.pm
installdirs:  vendor
requires:
    Net::BitTorrent::LibBTT:       0.016

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
